service: ignitecertification

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local
  
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - local
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
  bucket: serverlesscertificationignite


provider: 
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"



functions:
  genereteCertificate:
    handler: src/functions/genereteCertificate.handle
    events:
      - http:
          path: /genereteCertificate
          method: POST
          cors: true
  
  verifyCertificate:
    handler: src/functions/verifyCertificate.handle
    events:
      - http:
          path: /verifyCertificate/{id}
          method: GET
          cors: true

resources:
  Resources:
    dbCertificateUser:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_certificates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5