service: ignitecertification

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - local
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
  bucket: serverlesscertificationignite


provider: 
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"


functions:
  genereteCertificate:
    handler: src/functions/genereteCertificate.handle
    events:
      - http:
          path: /genereteCertificate
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/users_certificates"
  
  verifyCertificate:
    handler: src/functions/verifyCertificate.handle
    events:
      - http:
          path: /verifyCertificate/{id}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/users_certificates"


resources:
  Resources:
    dbCertificateUser:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_certificates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5